# Generated by Django 3.2.6 on 2021-09-01 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_client_name', models.CharField(blank=True, max_length=50, null=True)),
                ('default_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('default_contact_number', models.CharField(blank=True, max_length=14, null=True)),
                ('default_venue_name', models.CharField(blank=True, max_length=50, null=True)),
                ('default_venue_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('default_venue_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('default_county', models.CharField(blank=True, max_length=80, null=True)),
                ('default_postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('default_wedding_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
