# Generated by Django 3.2.6 on 2021-09-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_wedding_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
