# Generated by Django 3.2.6 on 2021-08-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_auto_20210815_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='tagline',
        ),
        migrations.AddField(
            model_name='band',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
            preserve_default=False,
        ),
    ]
