# Generated by Django 3.2.6 on 2021-09-24 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0006_rename_bandreviews_bandreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandreview',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
