# Generated by Django 3.2.6 on 2021-09-25 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0008_remove_band_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bandreview',
            old_name='author',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='bandreview',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.band'),
        ),
    ]
