# Generated by Django 3.2.6 on 2021-09-26 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0009_auto_20210925_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bands.category'),
        ),
    ]
