# Generated by Django 3.2.6 on 2021-09-26 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0010_alter_band_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandreview',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bands.band'),
        ),
    ]
