# Generated by Django 3.2.6 on 2021-08-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newbooking',
            name='duration',
        ),
        migrations.AlterField(
            model_name='newbooking',
            name='wedding_date',
            field=models.DateField(),
        ),
    ]
