# Generated by Django 3.2.6 on 2021-09-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_newbooking_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newbooking',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='newbooking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
