# Generated by Django 3.2.6 on 2021-09-25 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0008_remove_band_rating'),
        ('bookings', '0006_auto_20210905_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbooking',
            name='band_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bands.band'),
        ),
    ]
