# Generated by Django 3.2.6 on 2021-09-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_newbooking_band_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newbooking',
            old_name='band_id',
            new_name='band',
        ),
        migrations.RemoveField(
            model_name='newbooking',
            name='band_name',
        ),
    ]
