# Generated by Django 3.2.6 on 2021-09-25 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0008_remove_band_rating'),
        ('bookings', '0008_auto_20210925_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbooking',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.band'),
        ),
    ]
